### ISSUE TITLE
Clean Up Styles and Props

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/calendar-condenser#16]
**Is your feature request related to a problem? Please describe.**
The code base is a bit of a mess because we were all doing front end during the last couple of weeks.

**Describe the solution you'd like**
-  All styles should be moved to a central stylesheet, and should be passed as props from parent to child.
-  The state object should be de-structured for easier access
-  Each component should have its own interface, that contains only the props that are required.

**Comment by camrongrant1** [comment]
Could you be a little more specific on what you need me to do? I'm working on it right now

**Comment by andrewdimmer** [comment]
Please move all of the class names to `front-end-web/src/Styles/index.ts`, make sure that elements of the same basic type have the same className, and then adjust the props like on the Export Page so that they only call the functions and state elements that they need.
